name: emartstore
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.2+2

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:

  firebase_core: ^1.24.0
  cloud_firestore: ^3.5.1
  firebase_auth: ^3.11.2
  firebase_storage: ^10.3.11
  firebase_crashlytics: ^2.8.13
  firebase_messaging: ^13.1.0
  place_picker: ^0.10.0
  smooth_page_indicator: ^1.0.0+2
  shared_preferences: ^2.0.15
  image_picker: ^0.8.6
  image_gallery_saver: ^1.7.1
  progress_dialog:
    git:
      url: https://github.com/mostafaAbdelazim/progress_dialog.git
  intl: ^0.17.0
  cached_network_image: ^3.2.3
  flutter_facebook_auth: ^5.0.7
  intl_phone_number_input: ^0.7.2
  pin_code_fields: ^7.4.0
  easy_localization: ^3.0.1
  font_awesome_flutter: ^10.3.0
  photo_view: ^0.14.0
  flutter_native_image: ^0.0.6+1
  the_apple_sign_in: ^1.1.1
  numberpicker: ^2.1.1
  geolocator: ^9.0.2
  location: ^4.4.0
  geocoding: ^2.0.5
  dotted_border: ^2.0.0+3
  flutter_facebook_keyhash: ^0.0.4
  firebase_core_platform_interface: 4.5.1
  datetime_picker_formfield:
  geoflutterfire: ^3.0.3
  video_player: ^2.4.10
  flutter_sound: ^9.2.13
  video_thumbnail: ^0.5.3
  video_compress: ^3.1.2
  path_provider: ^2.0.11
  sticky_headers: ^0.3.0+2
  barcode_image: ^2.0.2
  image: ^3.2.0
  flutter_native_splash: ^2.2.16
  permission_handler: ^10.2.0
  google_maps_flutter: ^2.2.3
  dropdown_search: ^5.0.5
  audioplayers: ^1.2.0
  esc_pos_utils:
  bluetooth_thermal_printer:
  flutter_widget_from_html: ^0.9.1
  flutter_rating_bar: ^4.0.1

  # geocoder:
  #   git:
  #     https://github.com/aloisdeniel/flutter_geocoder.git

  # google_map_location_picker:
  #   git:
  #     url: git://github.com/lyokone/google_map_location_picker.git
  # permission_handler:
  # google_maps_flutter:
  # geocoder: any
  # geocoder:
  #   git:
  #     https://github.com/aloisdeniel/flutter_geocoder.git

dev_dependencies:
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/app_logo.png"
  remove_alpha_ios: true


flutter_native_splash:
  color: "#ffffff"
  image: assets/images/app_logo.png
  image_dark: assets/images/app_logo.png

  android_12:
    image: assets/images/app_logo.png
    image_dark: assets/images/app_logo.png

  web: false

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/audio/
    - assets/translations/
    - assets/flags/

  fonts:
    - family: Poppinsb
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf

    - family: Poppinsl
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf

    - family: Poppinsm
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf

    - family: Poppinsr
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    
    - family: Poppinssb
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf