name: emartdriver
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.2+2

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_messaging: ^13.0.4
  shared_preferences: ^2.0.15
  firebase_core: ^1.24.0
  firebase_auth: ^3.11.0
  cloud_firestore: ^3.5.1
  image_picker: ^0.8.6
  firebase_storage: ^10.3.10
  geoflutterfire: ^3.0.3
  progress_dialog:
    git:
      url: https://github.com/mostafaAbdelazim/progress_dialog.git
  provider: ^6.0.4
  url_launcher: ^6.1.7
  intl: ^0.17.0
  cached_network_image: ^3.2.2
  uuid: ^3.0.7
  video_thumbnail: ^0.5.3
  path_provider: ^2.0.11
  photo_view: ^0.14.0
  video_player: ^2.4.8
  flutter_facebook_auth: ^5.0.6
  http: ^0.13.5
  geolocator: ^9.0.2
  smooth_page_indicator: ^1.0.0+2
  intl_phone_number_input: ^0.7.1
  pin_code_fields: ^7.4.0
  permission_handler: ^10.2.0
  easy_localization: ^3.0.1
  google_maps_flutter: ^2.2.1
  flutter_polyline_points: ^1.0.0
  cupertino_icons: ^1.0.5
  flutter_native_image: ^0.0.6+1
  flutter_sound: ^9.2.13
  the_apple_sign_in: ^1.1.1
  video_compress: ^3.1.2
  location: ^4.4.0
  flutter_native_splash: ^2.2.15
  flutter_otp_text_field: ^1.1.1
  audioplayers: ^1.1.1
  flutter_rating_bar: ^4.0.1
  flutter_widget_from_html: ^0.9.0+1
  cloud_functions: ^3.3.9

dev_dependencies:
  flutter_launcher_icons: ^0.11.0

dependency_overrides:
  firebase_core_platform_interface: 4.5.1

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/app_logo.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/app_logo.png
  image_dark: assets/images/app_logo.png

  android_12:
    image: assets/images/app_logo.png
    image_dark: assets/images/app_logo.png

  web: false


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/translations/
    - assets/fonts/
    - assets/flags/
    - assets/audio/

  fonts:
    - family: Poppinsb
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf

    - family: Poppinsl
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf

    - family: Poppinsm
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf

    - family: Poppinsr
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    
    - family: Poppinssb
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf